### ISSUE TITLE
vivo android 11 手机无法搜索到其他手机

### ISSUE THREAD

**Issue by AnserBaby** [gpfduoduo/AnyShareOfAndroid#6]
三个问题：
1、需要接收方先开启雷达图，发送方才可以搜索到对方
2、接收方退出雷达图后，发送方依然显示在线
3、有一个警告
`java.lang.IllegalStateException: Handler (com.guo.duoduo.p2pmanager.p2pcore.MelonHandler) {e256b38} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:560)
        at android.os.Handler.enqueueMessage(Handler.java:778)
        at android.os.Handler.sendMessageAtTime(Handler.java:727)
        at android.os.Handler.sendMessageDelayed(Handler.java:697)
        at android.os.Handler.sendMessage(Handler.java:635)
        at com.guo.duoduo.p2pmanager.p2pcore.MelonHandler.send2Handler(MelonHandler.java:136)
        at com.guo.duoduo.p2pmanager.p2pcore.MelonCommunicate.run(MelonCommunicate.java:186)`

**Comment by callmexiaolu** [comment]
陆凯琪先生已经收到您的邮件，会尽快回复您！谢谢！
